apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chatbot-virtual-server
spec:
  hosts:
  - "*"
  gateways:
  - chatbot-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: chatbot-server-service
        port:
          number: 8000
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chabot-destination-rule-server
spec:
  host: chatbot-server-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100       


