apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chatbot-virtual-client2
spec:
  hosts:
  - "*"
  gateways:
  - chatbot-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: chatbot-client2-service
        port:
          number: 80
     

--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chatbot-virtual-client
spec:
  hosts:
  - "*"
  gateways:
  - chatbot-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: chatbot-client-service
        port:
          number: 80
     

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chabot-destination-rule-client
spec:
  host: chatbot-client-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection: # Circuit Breakers HAVE TO BE SWITCHED ON
      maxEjectionPercent: 100
      consecutive5xxErrors: 2
      interval: 10s
      baseEjectionTime: 30s    

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chabot-destination-rule-client2
spec:
  host: chatbot-client2-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection: 
      maxEjectionPercent: 100
      consecutive5xxErrors: 2
      interval: 10s
      baseEjectionTime: 30s    
